[package]
name = "oscilloscope_waveform"
version = "0.1.0"
edition = "2021"

[dependencies]
visa-rs = "0.6.2"
plotters = "0.3.7"
log = "0.4.22"
env_logger = "0.11.6"
anyhow = "1.0.95"
byteorder = "1.5"
